### ISSUE TITLE
Error on line 5 of Facade

### ISSUE THREAD

**Issue by uvassal** [lcmaquino/googleoauth2#1]
Hi,
  i think that you you have forget a char into line 5 of 
https://github.com/lcmaquino/googleoauth2/tree/main/src/Facades/GoogleOAuth2.php
the row

`use Lcmaquino\GoogleOAuth2\GoogleOAuthManager;`

give error, i have correct into

`use Lcmaquino\GoogleOAuth2\GoogleOAuth2Manager;`

**Comment by lcmaquino** [comment]
Hi @uvassal ,

This typo was fixed.

Thanks!
